name: the-power-workflow-simple
on:
  workflow_dispatch:
  workflow_call:
  repository_dispatch:
    types: [custom_event_type]
jobs:
  blank:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "test if output gets set and appears in the env" 
      - name: step2
        run: echo "output=wooo" >> $GITHUB_ENV
      - name: step3
        run: echo $GITHUB_ENV
      - name: step4
        run: echo ${{ env.output }}
